# Computer Lab Exercises week 4 (Solutions)

* These lab exercises give practice in using regular expressions.  https://www.w3schools.com/python/python_regex.asp
* These exercises are **not** part of the assessment of the Module.
* I will post the solutions roughly 1 week after this file has been uploaded to the DLE.


* See https://sites.google.com/view/pythonforstemstudents/home for a collection of links to information on python.


##  Question 0) Some more manipulation of string

Use the join string function (https://www.w3schools.com/python/ref_string_join.asp) to combine the list of strings into one single string that is printed out  


In [1]:
store = [ "The",  "future" , "of" , "money" , "is" , "bitcoin" ] 

ans = " ".join(store)

print(ans)


The future of money is bitcoin


## Question 1a)

* Modify the script so that the search for the word **hot** is at the end of the string. 

In [2]:
import re
xxx =  "The mustard was very hot"

if re.search("cold", xxx) :
    print(xxx)


In [3]:
# Put your solution here

import re
xxx =  "The mustard was very hot"

if re.search("hot$", xxx) :
    print(xxx)



The mustard was very hot


## Question 1b)

* Create a regular expression that matches a credit card number of  1234-5678-9000-1101 
* The check should match for the **OK** numbers and fail for the **FAIL** numbers

The output should look like:
<pre>
The format is correct for  1234-5678-9000-1101
The format is correct for  1224-5172-9304-1121
1245 5619 2722 7890 is not a credit card number
121563921227241 is not a credit card number
</pre>


In [4]:
# Put your solution here
credit_numberA = "1234-5678-9000-1101"  # OK
credit_numberB = "1224-5172-9304-1121"  # OK

not_credit_numberA = "1245 5619 2722 7890" # FAIL
not_credit_numberB = "121563921227241" # FAIL


In [5]:
credit_numberA = "1234-5678-9000-1101"  # OK
credit_numberB = "1224-5172-9304-1121"  # OK

not_credit_numberA = "1245 5619 2722 7890" # FAIL
not_credit_numberB = "121563921227241" # FAIL


for xxx in [credit_numberA, credit_numberB, not_credit_numberA, not_credit_numberB] : 
  if re.search(r"\d\d\d\d-\d\d\d\d-\d\d\d\d-\d\d\d\d", xxx) :
    print("The format is correct for " , xxx)
  else:
    print(xxx, "is not a credit card number")


The format is correct for  1234-5678-9000-1101
The format is correct for  1224-5172-9304-1121
1245 5619 2722 7890 is not a credit card number
121563921227241 is not a credit card number


##  Question 2


This exercise is an example of using regular expressions to 
match parts of strings. The python code below prints 
out part of the wikipedia page for Devon.

I am asking you to use regular expressions
(see https://www.tutorialspoint.com/python/python_reg_expressions.htm
and the lecture notes) to find the line number, which match conditions.

* Q1 Print the line, which starts with **To**.
* Q2 Print the line, which ends with **hilly**.
* Q3 Select the line with numbers on it.
* Q4 Select the line with two and.

As an example I show Q0 which matches **granite**

In [6]:
import re

data = [ "The north and south coasts of Devon each have both cliffs and sandy shores." , 
    "The inland terrain is rural, and generally hilly.",
    "Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).",
    "Its moorland extends across a large expanse of granite bedrock.",
    "To the north of Dartmoor are the Culm Measures and Exmoor.",   
    "In the valleys and lowlands of south and east Devon the soil is more fertile."
 ] 

for count,xxx in enumerate(data) :
   print("line[", count, "]=",  xxx) 
   if re.search("granite", xxx)  :
       print("Answer to question 0 on line ", count)

line[ 0 ]= The north and south coasts of Devon each have both cliffs and sandy shores.
line[ 1 ]= The inland terrain is rural, and generally hilly.
line[ 2 ]= Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).
line[ 3 ]= Its moorland extends across a large expanse of granite bedrock.
Answer to question 0 on line  3
line[ 4 ]= To the north of Dartmoor are the Culm Measures and Exmoor.
line[ 5 ]= In the valleys and lowlands of south and east Devon the soil is more fertile.


In [7]:
import re

data = [ "The north and south coasts of Devon each have both cliffs and sandy shores." , 
    "The inland terrain is rural, and generally hilly.",
    "Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).",
    "Its moorland extends across a large expanse of granite bedrock.",
    "To the north of Dartmoor are the Culm Measures and Exmoor.",   
    "In the valleys and lowlands of south and east Devon the soil is more fertile."
 ] 

print("Answers ")
for count,xxx in enumerate(data) :
   print("line[", count, "]=",  xxx) 
   if re.search("granite", xxx)  :
       print("Answer to question 0 on line ", count)
   if re.search("^To", xxx)  :
       print("Answer to question 1 on line ", count)
   if re.search("hilly.$", xxx)  :
       print("Answer to question 2 on line ", count)
   if re.search("[0-9][0-9][0-9]" , xxx) :
       print("Answer to question 3 on line ", count)
   if re.search(r" and.*and" , xxx) :
       # the space is required so that inland is not mached
       print("Answer to question 4 on line ", count)



Answers 
line[ 0 ]= The north and south coasts of Devon each have both cliffs and sandy shores.
Answer to question 4 on line  0
line[ 1 ]= The inland terrain is rural, and generally hilly.
Answer to question 2 on line  1
line[ 2 ]= Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).
Answer to question 3 on line  2
line[ 3 ]= Its moorland extends across a large expanse of granite bedrock.
Answer to question 0 on line  3
line[ 4 ]= To the north of Dartmoor are the Culm Measures and Exmoor.
Answer to question 1 on line  4
line[ 5 ]= In the valleys and lowlands of south and east Devon the soil is more fertile.
Answer to question 4 on line  5


The output from my code is:
<pre>
line[ 0 ]= The north and south coasts of Devon each have both cliffs and sandy shores.
Answer to question 4 on line  0
line[ 1 ]= The inland terrain is rural, and generally hilly.
Answer to question 2 on line  1
line[ 2 ]= Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).
Answer to question 3 on line  2
line[ 3 ]= Its moorland extends across a large expanse of granite bedrock.
line[ 4 ]= To the north of Dartmoor are the Culm Measures and Exmoor.
Answer to question 1 on line  4
line[ 5 ]= In the valleys and lowlands of south and east Devon the soil is more fertile.
Answer to question 4 on line  5
</pre>


I recommend you also explore using the wikipedia module
https://stackabuse.com/getting-started-with-pythons-wikipedia-api/
to download content from Wikipedia. This is NOT part of the exercise,
but it is the natural next step.

##  Question 3 (more regular expressions)
* The example below is a python script to extract email addresses from the string **input**
* Unfortunately the script only finds two emails
* Modify the script to extract all the emails.
* I would start by understanding the regular expression in **findall**

In [8]:
import re

input_ = """
My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com
"""
print("--------------------------------------------------")
print(input_)
print("--------------------------------------------------")

# modify this line
email = re.findall(r'\b\w*\.\w*@\w*\.\w*.\w*\b' , input_)

print("Extracted emails")
for tuple in email:
    print(tuple) 

--------------------------------------------------

My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com

--------------------------------------------------
Extracted emails
yyy.dong@plymouth.ac.uk
richard.gggg@plymouth.ac.uk


In [9]:
# One Solution
import re

input_ = """
My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com
"""
print("--------------------------------------------------")
print(input_)
print("--------------------------------------------------")

# modify this line
email = re.findall(r'\b\w*\.\w*@\w*\.\w*.\w*\b|\b\w*@\w*\.\w*.\w*\b' , input_)
# The solution uses the |  or function to match two patterns

print("Extracted emails")
for tuple in email:
    print(tuple) 

--------------------------------------------------

My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com

--------------------------------------------------
Extracted emails
yyy.dong@plymouth.ac.uk
richard.gggg@plymouth.ac.uk
gggg@gmail.com
jjj@hotmail.com
gig@yahoo.com


In [10]:
# another solution
import re

input_ = """
My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com
"""
print("--------------------------------------------------")
print(input_)
print("--------------------------------------------------")

# modify this line

email = re.findall(r'\b[a-z\.]*@[a-z\.]*\b' , input_)
#  This matches start_of_word multiple copies letter. @ multiple copies letter. end_


print("Extracted emails")
for tuple in email:
    print(tuple) 

--------------------------------------------------

My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com

--------------------------------------------------
Extracted emails
yyy.dong@plymouth.ac.uk
richard.gggg@plymouth.ac.uk
gggg@gmail.com
jjj@hotmail.com
gig@yahoo.com


The goal is use regular expressions to extract all the email
addresses in a string variable.

This exercise is an example of using regular expressions to 
match parts of strings. The above python code extracts some
of the email addresses from the string **input**.
The regular expression matches emails of the form:
letters-or-numbers.letters-or-numberse@letters-or-numbers.letters-or-numbers.letters-or-numbers .
The command "\b" matches the spacing between words.

The current python code does not extract all the email addresses, so
the task is to modify the regular expression so that the python
extracts all the email addresses. See
https://www.tutorialspoint.com/python/python_reg_expressions.htm
and the lecture notes.



## Question  4  (Harder)
*  The csv file resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv contains information about Devon companies. The file is available on the DLE.
*  The data set is from  https://plymouth.thedata.place/dataset/devon-businesses 

The exercise is to check the post codes in the csv file. For example the enteries in column **RegAddress.PostCode**  and column **Pcodelookup**. 

* Modify the code below to count the number of times the **RegAddress.PostCode** and **Pcodelookup** are different (after removing any spaces). 

* Also print out the **CompanyNumber** when the postcode is not in the correct format. https://ideal-postcodes.co.uk/guides/uk-postcode-format To simplify the problem just assume that the postcode is a combination of letters and numbers.


Just for information you can look up information about companies using  https://find-and-update.company-information.service.gov.uk/?_ga=2.26241021.174329778.1666023410-664048164.1666023410

In [1]:
# Modify this code
import csv
import re
name = "resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv"
print("Readng the data from " , name)

count = 0 
store = []
with open(name,encoding="ISO-8859-1") as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    next(readCSV) 
    for row in readCSV:

                    company_no     = row[0]
                    postcode       = row[6].replace(" ","")
                    postcode_regen = row[18].replace(" ","")


print("---------------")

print("The number of mismatched postcodes " , count)
print("Incorrect postcode format")
store.sort()
for ss in store :
    print(ss)


Readng the data from  resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv
---------------
The number of mismatched postcodes  0
Incorrect postcode format


In [2]:
import csv
import re
name = "resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv"
print("Readng the data from " , name)

count = 0 
store = []
with open(name,encoding="ISO-8859-1") as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    next(readCSV) 
    for row in readCSV:

                    company_no     = row[0]
                    postcode       = row[6].replace(" ","")
                    postcode_regen = row[18].replace(" ","")

                    if not re.search(r"\D", postcode) :
#                       print("Problem " , postcode, company_no )
                       store.append(company_no)
        
                    if postcode != postcode_regen :
#                         print(company_no, postcode, postcode_regen)
#                         print(company_no, end = " ")         
                        count += 1

print("---------------")

print("The number of mismatched postcodes " , count)
print("Incorrect postcode format")
store.sort()
for ss in store :
    print(ss)


Readng the data from  resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv
---------------
The number of mismatched postcodes  15289
Incorrect postcode format
1118335
1171193
1378536
1520456
1529593
1753725
1830071
1995238
2244084
2323873
2347461
2444710
2466331
2751673
2908967
2935942
2958290
3168499
3277650
3348176
3417575
3613533
3918945
4199124
4417100
4431782
4443441
4779348
4868976
491948
5001799
5250887
5641904
5977493
622016
6533166
6666870
6938846
6941269
6974710
7040903
7173057
7194265
7249459
7471464
7508506
7647283
7736174
7839506
7923087
797171
815002
8268515
8334285
8356735
8387072
8387321
8435824
8497744
8637339
8665905
8747169
8922099
8936853
8958307
8986337
8999824
9219367
9249650
9267908
9370354
9470056
9513535
9593599
9628293
9700761
9835930
9946231
9952620
IP15001R
LP003582
LP003944
LP004184
LP004236
LP004323
LP004429
LP004441
LP004929
LP010271
LP013051
OC349965
OC398588


## Qustion 5 (Interview questions)

* Sometimes in technical interviews, the candidate is asked some basic questions on python.
* See https://uk.indeed.com/career-advice/interviewing/python-interview-questions for an example. Note that we will cover some of the technical issues as the course continues.



### Question 5a

What is a Negative Index in a list in Python?

In [13]:
xx = [ "a" , "b" , "c" , "d"]
print(xx[-1])

d


The negative index is elements from the end of the list
For example x[-1] is the last element of a list
For example x[-2] is the second to last element of a list

### Question 5b

How the string does get converted to a number?

In [14]:
xx = "3.14"

xxf = float(xx)

print(xxf)

3.14


The float function converts a string to a number

### Question 5c

When to use a tuple vs list vs dictionary in Python?

* Use a tuple to store a sequence of items that will not change.

* Use a list to store a sequence of items that may change.

* Use a dictionary when you want to associate pairs of two items.